/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\myBlog\\docs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-4632fa65",
    path: "/pages/CSS3/css3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4632fa65").then(next)
    },
  },
  {
    name: "v-74bb3ed4",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74bb3ed4").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-2c7993aa",
    path: "/pages/HTML5/html5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c7993aa").then(next)
    },
  },
  {
    name: "v-97ef0592",
    path: "/pages/VUE2.0/03_%E5%B8%B8%E7%94%A8%E6%8C%87%E4%BB%A4%E4%BD%BF%E7%94%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-97ef0592").then(next)
    },
  },
  {
    path: "/pages/VUE2.0/03_常用指令使用.html",
    redirect: "/pages/VUE2.0/03_%E5%B8%B8%E7%94%A8%E6%8C%87%E4%BB%A4%E4%BD%BF%E7%94%A8.html"
  },
  {
    path: "/pages/VUE2.0/03_常用指令使用.html",
    redirect: "/pages/VUE2.0/03_%E5%B8%B8%E7%94%A8%E6%8C%87%E4%BB%A4%E4%BD%BF%E7%94%A8.html"
  },
  {
    name: "v-9bf7d3aa",
    path: "/pages/VUE2.0/02_Vue%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9bf7d3aa").then(next)
    },
  },
  {
    path: "/pages/VUE2.0/02_Vue核心概念.html",
    redirect: "/pages/VUE2.0/02_Vue%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5.html"
  },
  {
    path: "/pages/VUE2.0/02_Vue核心概念.html",
    redirect: "/pages/VUE2.0/02_Vue%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5.html"
  },
  {
    name: "v-da7c0ce4",
    path: "/pages/VUE2.0/05_%E8%AE%A1%E7%AE%97%E5%B1%9E%E6%80%A7%E4%B8%8E%E7%9B%91%E5%90%AC%E5%99%A8%E3%80%81Vue%E5%AE%9E%E4%BE%8B%E7%9A%84%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-da7c0ce4").then(next)
    },
  },
  {
    path: "/pages/VUE2.0/05_计算属性与监听器、Vue实例的生命周期.html",
    redirect: "/pages/VUE2.0/05_%E8%AE%A1%E7%AE%97%E5%B1%9E%E6%80%A7%E4%B8%8E%E7%9B%91%E5%90%AC%E5%99%A8%E3%80%81Vue%E5%AE%9E%E4%BE%8B%E7%9A%84%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F.html"
  },
  {
    path: "/pages/VUE2.0/05_计算属性与监听器、Vue实例的生命周期.html",
    redirect: "/pages/VUE2.0/05_%E8%AE%A1%E7%AE%97%E5%B1%9E%E6%80%A7%E4%B8%8E%E7%9B%91%E5%90%AC%E5%99%A8%E3%80%81Vue%E5%AE%9E%E4%BE%8B%E7%9A%84%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F.html"
  },
  {
    name: "v-904c4292",
    path: "/pages/VUE2.0/07_%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8C%87%E4%BB%A4%E5%8F%8A%E8%BF%87%E6%B8%A1%EF%BC%88%E5%8A%A8%E7%94%BB%EF%BC%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-904c4292").then(next)
    },
  },
  {
    path: "/pages/VUE2.0/07_自定义指令及过渡（动画）.html",
    redirect: "/pages/VUE2.0/07_%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8C%87%E4%BB%A4%E5%8F%8A%E8%BF%87%E6%B8%A1%EF%BC%88%E5%8A%A8%E7%94%BB%EF%BC%89.html"
  },
  {
    path: "/pages/VUE2.0/07_自定义指令及过渡（动画）.html",
    redirect: "/pages/VUE2.0/07_%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8C%87%E4%BB%A4%E5%8F%8A%E8%BF%87%E6%B8%A1%EF%BC%88%E5%8A%A8%E7%94%BB%EF%BC%89.html"
  },
  {
    name: "v-816bb714",
    path: "/pages/VUE2.0/06_Vue%E5%AE%9E%E4%BE%8B%E5%B8%B8%E7%94%A8%E7%9A%84%E5%B1%9E%E6%80%A7%E5%92%8C%E6%96%B9%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-816bb714").then(next)
    },
  },
  {
    path: "/pages/VUE2.0/06_Vue实例常用的属性和方法.html",
    redirect: "/pages/VUE2.0/06_Vue%E5%AE%9E%E4%BE%8B%E5%B8%B8%E7%94%A8%E7%9A%84%E5%B1%9E%E6%80%A7%E5%92%8C%E6%96%B9%E6%B3%95.html"
  },
  {
    path: "/pages/VUE2.0/06_Vue实例常用的属性和方法.html",
    redirect: "/pages/VUE2.0/06_Vue%E5%AE%9E%E4%BE%8B%E5%B8%B8%E7%94%A8%E7%9A%84%E5%B1%9E%E6%80%A7%E5%92%8C%E6%96%B9%E6%B3%95.html"
  },
  {
    name: "v-68d4cac8",
    path: "/pages/VUE2.0/01_NPM%E5%8C%85%E7%9A%84%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68d4cac8").then(next)
    },
  },
  {
    path: "/pages/VUE2.0/01_NPM包的安装与使用.html",
    redirect: "/pages/VUE2.0/01_NPM%E5%8C%85%E7%9A%84%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8.html"
  },
  {
    path: "/pages/VUE2.0/01_NPM包的安装与使用.html",
    redirect: "/pages/VUE2.0/01_NPM%E5%8C%85%E7%9A%84%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8.html"
  },
  {
    name: "v-10cba786",
    path: "/pages/VUE2.0/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-10cba786").then(next)
    },
  },
  {
    path: "/pages/VUE2.0/index.html",
    redirect: "/pages/VUE2.0/"
  },
  {
    name: "v-f44c8566",
    path: "/pages/VUE2.0/09_%E7%BB%84%E4%BB%B6%E5%8F%8A%E7%BB%84%E4%BB%B6%E4%B9%8B%E9%97%B4%E7%9A%84%E9%80%9A%E4%BF%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f44c8566").then(next)
    },
  },
  {
    path: "/pages/VUE2.0/09_组件及组件之间的通信.html",
    redirect: "/pages/VUE2.0/09_%E7%BB%84%E4%BB%B6%E5%8F%8A%E7%BB%84%E4%BB%B6%E4%B9%8B%E9%97%B4%E7%9A%84%E9%80%9A%E4%BF%A1.html"
  },
  {
    path: "/pages/VUE2.0/09_组件及组件之间的通信.html",
    redirect: "/pages/VUE2.0/09_%E7%BB%84%E4%BB%B6%E5%8F%8A%E7%BB%84%E4%BB%B6%E4%B9%8B%E9%97%B4%E7%9A%84%E9%80%9A%E4%BF%A1.html"
  },
  {
    name: "v-05061389",
    path: "/pages/VUE2.0/04_%E4%BA%8B%E4%BB%B6%E4%BF%AE%E9%A5%B0%E7%AC%A6%E3%80%81%E6%8C%89%E9%94%AE%E4%BF%AE%E9%A5%B0%E7%AC%A6%E4%B8%8E%E7%B3%BB%E7%BB%9F%E4%BF%AE%E9%A5%B0%E7%AC%A6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05061389").then(next)
    },
  },
  {
    path: "/pages/VUE2.0/04_事件修饰符、按键修饰符与系统修饰符.html",
    redirect: "/pages/VUE2.0/04_%E4%BA%8B%E4%BB%B6%E4%BF%AE%E9%A5%B0%E7%AC%A6%E3%80%81%E6%8C%89%E9%94%AE%E4%BF%AE%E9%A5%B0%E7%AC%A6%E4%B8%8E%E7%B3%BB%E7%BB%9F%E4%BF%AE%E9%A5%B0%E7%AC%A6.html"
  },
  {
    path: "/pages/VUE2.0/04_事件修饰符、按键修饰符与系统修饰符.html",
    redirect: "/pages/VUE2.0/04_%E4%BA%8B%E4%BB%B6%E4%BF%AE%E9%A5%B0%E7%AC%A6%E3%80%81%E6%8C%89%E9%94%AE%E4%BF%AE%E9%A5%B0%E7%AC%A6%E4%B8%8E%E7%B3%BB%E7%BB%9F%E4%BF%AE%E9%A5%B0%E7%AC%A6.html"
  },
  {
    name: "v-0cdd67c0",
    path: "/pages/VUE2.0/08_%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%87%E6%BB%A4%E5%99%A8%E5%8F%8A%E5%BC%80%E5%8F%91%E6%8F%92%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0cdd67c0").then(next)
    },
  },
  {
    path: "/pages/VUE2.0/08_自定义过滤器及开发插件.html",
    redirect: "/pages/VUE2.0/08_%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%87%E6%BB%A4%E5%99%A8%E5%8F%8A%E5%BC%80%E5%8F%91%E6%8F%92%E4%BB%B6.html"
  },
  {
    path: "/pages/VUE2.0/08_自定义过滤器及开发插件.html",
    redirect: "/pages/VUE2.0/08_%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%87%E6%BB%A4%E5%99%A8%E5%8F%8A%E5%BC%80%E5%8F%91%E6%8F%92%E4%BB%B6.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-322a45da",
    path: "/tag/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-322a45da").then(next)
    },
    meta: {"pid":"tags","id":"vue"}
  },
  {
    path: "/tag/vue/index.html",
    redirect: "/tag/vue/"
  },
  {
    name: "v-41e61d1f",
    path: "/categories/frontEnd/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-41e61d1f").then(next)
    },
    meta: {"pid":"categories","id":"frontEnd"}
  },
  {
    path: "/categories/frontEnd/index.html",
    redirect: "/categories/frontEnd/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]