/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "星辰大海",
  "description": "日月星辰，山川大海",
  "base": "/docs/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "icon-mianxingniuyouguo"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "星辰大海的博客"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "vuepress介绍 vuepress说明，星辰大海的博客"
      }
    ]
  ],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/pages/CSS3/css3.html",
      "relativePath": "pages/CSS3/css3.md",
      "key": "v-4632fa65",
      "path": "/pages/CSS3/css3.html"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/niuyouguo.png",
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-74bb3ed4",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/pages/HTML5/html5.html",
      "relativePath": "pages/HTML5/html5.md",
      "key": "v-2c7993aa",
      "path": "/pages/HTML5/html5.html"
    },
    {
      "title": "常用指令使用",
      "frontmatter": {
        "title": "常用指令使用",
        "date": "2022-9-16",
        "categories": [
          "frontEnd"
        ],
        "tags": [
          "vue"
        ]
      },
      "regularPath": "/pages/VUE2.0/03_%E5%B8%B8%E7%94%A8%E6%8C%87%E4%BB%A4%E4%BD%BF%E7%94%A8.html",
      "relativePath": "pages/VUE2.0/03_常用指令使用.md",
      "key": "v-97ef0592",
      "path": "/pages/VUE2.0/03_%E5%B8%B8%E7%94%A8%E6%8C%87%E4%BB%A4%E4%BD%BF%E7%94%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "3.1 v-text与v-html指令",
          "slug": "_3-1-v-text与v-html指令"
        },
        {
          "level": 2,
          "title": "3.2 v-model指令",
          "slug": "_3-2-v-model指令"
        },
        {
          "level": 2,
          "title": "3.3 v-clock指令",
          "slug": "_3-3-v-clock指令"
        },
        {
          "level": 2,
          "title": "3.4 v-bind指令",
          "slug": "_3-4-v-bind指令"
        },
        {
          "level": 2,
          "title": "3.5 v-on指令",
          "slug": "_3-5-v-on指令"
        },
        {
          "level": 2,
          "title": "3.6 v-if指令",
          "slug": "_3-6-v-if指令"
        },
        {
          "level": 2,
          "title": "4.7 v-show指令",
          "slug": "_4-7-v-show指令"
        },
        {
          "level": 2,
          "title": "3.8 v-for指令",
          "slug": "_3-8-v-for指令"
        },
        {
          "level": 2,
          "title": "3.9 v-if与v-for指令结合使用",
          "slug": "_3-9-v-if与v-for指令结合使用"
        },
        {
          "level": 2,
          "title": "3.10 v-once与v-pre指令",
          "slug": "_3-10-v-once与v-pre指令"
        }
      ]
    },
    {
      "title": "Vue核心概念",
      "frontmatter": {
        "title": "Vue核心概念",
        "date": "2022-9-15",
        "categories": [
          "frontEnd"
        ],
        "tags": [
          "vue"
        ]
      },
      "regularPath": "/pages/VUE2.0/02_Vue%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5.html",
      "relativePath": "pages/VUE2.0/02_Vue核心概念.md",
      "key": "v-9bf7d3aa",
      "path": "/pages/VUE2.0/02_Vue%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5.html",
      "headers": [
        {
          "level": 2,
          "title": "2.1 Vue.js的基本认识",
          "slug": "_2-1-vue-js的基本认识"
        },
        {
          "level": 2,
          "title": "2.2 Vue.js的优点与核心思想",
          "slug": "_2-2-vue-js的优点与核心思想"
        },
        {
          "level": 2,
          "title": "3.4 MVVM框架概述",
          "slug": "_3-4-mvvm框架概述"
        }
      ]
    },
    {
      "title": "计算属性与监听器、Vue实例的生命周期",
      "frontmatter": {
        "title": "计算属性与监听器、Vue实例的生命周期",
        "date": "2022-9-19",
        "categories": [
          "frontEnd"
        ],
        "tags": [
          "vue"
        ]
      },
      "regularPath": "/pages/VUE2.0/05_%E8%AE%A1%E7%AE%97%E5%B1%9E%E6%80%A7%E4%B8%8E%E7%9B%91%E5%90%AC%E5%99%A8%E3%80%81Vue%E5%AE%9E%E4%BE%8B%E7%9A%84%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F.html",
      "relativePath": "pages/VUE2.0/05_计算属性与监听器、Vue实例的生命周期.md",
      "key": "v-da7c0ce4",
      "path": "/pages/VUE2.0/05_%E8%AE%A1%E7%AE%97%E5%B1%9E%E6%80%A7%E4%B8%8E%E7%9B%91%E5%90%AC%E5%99%A8%E3%80%81Vue%E5%AE%9E%E4%BE%8B%E7%9A%84%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F.html",
      "headers": [
        {
          "level": 2,
          "title": "5.1计算属性基础知识",
          "slug": "_5-1计算属性基础知识"
        },
        {
          "level": 2,
          "title": "5.2 计算属性的组成",
          "slug": "_5-2-计算属性的组成"
        },
        {
          "level": 2,
          "title": "5.3 属性计算与方法的对比",
          "slug": "_5-3-属性计算与方法的对比"
        },
        {
          "level": 2,
          "title": "5.4监听属性watch",
          "slug": "_5-4监听属性watch"
        },
        {
          "level": 2,
          "title": "5.5vm.$watch和watch使用总结",
          "slug": "_5-5vm-watch和watch使用总结"
        },
        {
          "level": 2,
          "title": "5.6 Vue实例生命周期",
          "slug": "_5-6-vue实例生命周期"
        },
        {
          "level": 3,
          "title": "5.6.1 Vue实例生命周期基础知识",
          "slug": "_5-6-1-vue实例生命周期基础知识"
        }
      ]
    },
    {
      "title": "自定义指令及过渡（动画）",
      "frontmatter": {
        "title": "自定义指令及过渡（动画）",
        "date": "2022-9-20",
        "categories": [
          "frontEnd"
        ],
        "tags": [
          "vue"
        ]
      },
      "regularPath": "/pages/VUE2.0/07_%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8C%87%E4%BB%A4%E5%8F%8A%E8%BF%87%E6%B8%A1%EF%BC%88%E5%8A%A8%E7%94%BB%EF%BC%89.html",
      "relativePath": "pages/VUE2.0/07_自定义指令及过渡（动画）.md",
      "key": "v-904c4292",
      "path": "/pages/VUE2.0/07_%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8C%87%E4%BB%A4%E5%8F%8A%E8%BF%87%E6%B8%A1%EF%BC%88%E5%8A%A8%E7%94%BB%EF%BC%89.html",
      "headers": [
        {
          "level": 2,
          "title": "7.1自定义指令",
          "slug": "_7-1自定义指令"
        },
        {
          "level": 2,
          "title": "7.2 过渡效果实现",
          "slug": "_7-2-过渡效果实现"
        }
      ]
    },
    {
      "title": "Vue实例常用的属性和方法",
      "frontmatter": {
        "title": "Vue实例常用的属性和方法",
        "date": "2022-9-20",
        "categories": [
          "frontEnd"
        ],
        "tags": [
          "vue"
        ]
      },
      "regularPath": "/pages/VUE2.0/06_Vue%E5%AE%9E%E4%BE%8B%E5%B8%B8%E7%94%A8%E7%9A%84%E5%B1%9E%E6%80%A7%E5%92%8C%E6%96%B9%E6%B3%95.html",
      "relativePath": "pages/VUE2.0/06_Vue实例常用的属性和方法.md",
      "key": "v-816bb714",
      "path": "/pages/VUE2.0/06_Vue%E5%AE%9E%E4%BE%8B%E5%B8%B8%E7%94%A8%E7%9A%84%E5%B1%9E%E6%80%A7%E5%92%8C%E6%96%B9%E6%B3%95.html",
      "headers": [
        {
          "level": 2,
          "title": "6.1 Vue实例常用属性",
          "slug": "_6-1-vue实例常用属性"
        },
        {
          "level": 2,
          "title": "Vue 实例常用方法",
          "slug": "vue-实例常用方法"
        }
      ]
    },
    {
      "title": "npm包的安装与使用",
      "frontmatter": {
        "title": "npm包的安装与使用",
        "date": "2022-9-14",
        "categories": [
          "frontEnd"
        ],
        "tags": [
          "vue"
        ]
      },
      "regularPath": "/pages/VUE2.0/01_NPM%E5%8C%85%E7%9A%84%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8.html",
      "relativePath": "pages/VUE2.0/01_NPM包的安装与使用.md",
      "key": "v-68d4cac8",
      "path": "/pages/VUE2.0/01_NPM%E5%8C%85%E7%9A%84%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "1.1 npm概述",
          "slug": "_1-1-npm概述"
        },
        {
          "level": 2,
          "title": "1.2 npm安装",
          "slug": "_1-2-npm安装"
        },
        {
          "level": 2,
          "title": "1.3 配置node环境(npm全局安装路径)",
          "slug": "_1-3-配置node环境-npm全局安装路径"
        },
        {
          "level": 2,
          "title": "1.4 通过npm初始化项目",
          "slug": "_1-4-通过npm初始化项目"
        },
        {
          "level": 2,
          "title": "1.5 安装模块（js库）",
          "slug": "_1-5-安装模块-js库"
        },
        {
          "level": 2,
          "title": "1.6 生产环境和开发环境依赖模块的安装",
          "slug": "_1-6-生产环境和开发环境依赖模块的安装"
        },
        {
          "level": 2,
          "title": "1.7 CNPM命令安装",
          "slug": "_1-7-cnpm命令安装"
        },
        {
          "level": 2,
          "title": "1.8批量下载模块",
          "slug": "_1-8批量下载模块"
        },
        {
          "level": 2,
          "title": "1.9 其他常用npm命令",
          "slug": "_1-9-其他常用npm命令"
        }
      ]
    },
    {
      "title": "Vue2.0",
      "frontmatter": {},
      "regularPath": "/pages/VUE2.0/",
      "relativePath": "pages/VUE2.0/README.md",
      "key": "v-10cba786",
      "path": "/pages/VUE2.0/",
      "headers": [
        {
          "level": 2,
          "title": "官方文档",
          "slug": "官方文档"
        }
      ]
    },
    {
      "title": "组件及组件之间的通信",
      "frontmatter": {
        "title": "组件及组件之间的通信",
        "date": "2022-9-21",
        "categories": [
          "frontEnd"
        ],
        "tags": [
          "vue"
        ]
      },
      "regularPath": "/pages/VUE2.0/09_%E7%BB%84%E4%BB%B6%E5%8F%8A%E7%BB%84%E4%BB%B6%E4%B9%8B%E9%97%B4%E7%9A%84%E9%80%9A%E4%BF%A1.html",
      "relativePath": "pages/VUE2.0/09_组件及组件之间的通信.md",
      "key": "v-f44c8566",
      "path": "/pages/VUE2.0/09_%E7%BB%84%E4%BB%B6%E5%8F%8A%E7%BB%84%E4%BB%B6%E4%B9%8B%E9%97%B4%E7%9A%84%E9%80%9A%E4%BF%A1.html",
      "headers": [
        {
          "level": 2,
          "title": "9.1组件的概念",
          "slug": "_9-1组件的概念"
        },
        {
          "level": 2,
          "title": "9.2 组件的注册及使用",
          "slug": "_9-2-组件的注册及使用"
        }
      ]
    },
    {
      "title": "事件修饰符、按键修饰符与系统修饰符",
      "frontmatter": {
        "title": "事件修饰符、按键修饰符与系统修饰符",
        "date": "2022-9-18",
        "categories": [
          "frontEnd"
        ],
        "tags": [
          "vue"
        ]
      },
      "regularPath": "/pages/VUE2.0/04_%E4%BA%8B%E4%BB%B6%E4%BF%AE%E9%A5%B0%E7%AC%A6%E3%80%81%E6%8C%89%E9%94%AE%E4%BF%AE%E9%A5%B0%E7%AC%A6%E4%B8%8E%E7%B3%BB%E7%BB%9F%E4%BF%AE%E9%A5%B0%E7%AC%A6.html",
      "relativePath": "pages/VUE2.0/04_事件修饰符、按键修饰符与系统修饰符.md",
      "key": "v-05061389",
      "path": "/pages/VUE2.0/04_%E4%BA%8B%E4%BB%B6%E4%BF%AE%E9%A5%B0%E7%AC%A6%E3%80%81%E6%8C%89%E9%94%AE%E4%BF%AE%E9%A5%B0%E7%AC%A6%E4%B8%8E%E7%B3%BB%E7%BB%9F%E4%BF%AE%E9%A5%B0%E7%AC%A6.html",
      "headers": [
        {
          "level": 2,
          "title": "4.1 DOM事件流相关概念",
          "slug": "_4-1-dom事件流相关概念"
        },
        {
          "level": 2,
          "title": "4.2 事件修饰符",
          "slug": "_4-2-事件修饰符"
        },
        {
          "level": 3,
          "title": "4.21 .stop修饰符",
          "slug": "_4-21-stop修饰符"
        },
        {
          "level": 3,
          "title": ".prevent修饰符",
          "slug": "prevent修饰符"
        },
        {
          "level": 3,
          "title": "4.2.3 capture修饰符",
          "slug": "_4-2-3-capture修饰符"
        },
        {
          "level": 3,
          "title": "4.2.4 .self修饰符",
          "slug": "_4-2-4-self修饰符"
        },
        {
          "level": 3,
          "title": "4.2.5 .once修饰符",
          "slug": "_4-2-5-once修饰符"
        },
        {
          "level": 2,
          "title": "4.3按键修饰符",
          "slug": "_4-3按键修饰符"
        },
        {
          "level": 3,
          "title": "4.3.1 获取按键的keyCode",
          "slug": "_4-3-1-获取按键的keycode"
        },
        {
          "level": 3,
          "title": "4.3.2 监听按键事件",
          "slug": "_4-3-2-监听按键事件"
        }
      ]
    },
    {
      "title": "自定义过滤器",
      "frontmatter": {
        "title": "自定义过滤器",
        "date": "2022-9-20",
        "categories": [
          "frontEnd"
        ],
        "tags": [
          "vue"
        ]
      },
      "regularPath": "/pages/VUE2.0/08_%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%87%E6%BB%A4%E5%99%A8%E5%8F%8A%E5%BC%80%E5%8F%91%E6%8F%92%E4%BB%B6.html",
      "relativePath": "pages/VUE2.0/08_自定义过滤器及开发插件.md",
      "key": "v-0cdd67c0",
      "path": "/pages/VUE2.0/08_%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%87%E6%BB%A4%E5%99%A8%E5%8F%8A%E5%BC%80%E5%8F%91%E6%8F%92%E4%BB%B6.html",
      "headers": [
        {
          "level": 2,
          "title": "8.1自定义过滤器",
          "slug": "_8-1自定义过滤器"
        },
        {
          "level": 2,
          "title": "8.2开发插件",
          "slug": "_8-2开发插件"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "vue Tags"
      },
      "regularPath": "/tag/vue/",
      "key": "v-322a45da",
      "path": "/tag/vue/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "frontEnd Categories"
      },
      "regularPath": "/categories/frontEnd/",
      "key": "v-41e61d1f",
      "path": "/categories/frontEnd/"
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/touxiang.png",
    "type": "blog",
    "huawei": true,
    "author": "山川大海",
    "smoothScroll": false,
    "nextLinks": true,
    "prevLinks": true,
    "blogConfig": {
      "tag": {
        "location": 2,
        "text": "标签"
      },
      "category": {
        "location": 2,
        "text": "分类"
      },
      "socialLinks": [
        {
          "icon": "reco-github",
          "link": "https://github.com/recoluan"
        },
        {
          "icon": "reco-npm",
          "link": "https://www.npmjs.com/~reco_luan"
        }
      ]
    },
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "分类",
        "icon": "reco-category",
        "items": [
          {
            "text": "Vue2.0",
            "link": "/pages/VUE2.0/"
          }
        ]
      },
      {
        "text": "文档",
        "icon": "reco-document",
        "items": [
          {
            "text": "React.js中文文档",
            "link": "https://zh-hans.reactjs.org/"
          },
          {
            "text": "Element ui文档",
            "link": "https://element.eleme.cn/#/zh-CN"
          },
          {
            "text": "微信小程序",
            "link": "https://developers.weixin.qq.com/miniprogram/dev/framework/"
          },
          {
            "text": "Node.js中文文档",
            "link": "http://nodejs.cn/learn"
          },
          {
            "text": "Git中文教程",
            "link": "https://git-scm.com/book/zh/v2"
          }
        ]
      },
      {
        "text": "工具箱",
        "icon": "icon-gongju",
        "items": [
          {
            "text": "菜鸟教程",
            "link": "https://www.runoob.com/"
          },
          {
            "text": "在线PS",
            "link": "https://www.uupoop.com/"
          },
          {
            "text": "奶牛快传",
            "link": "https://cowtransfer.com/"
          },
          {
            "text": "编程语言排行榜",
            "link": "https://www.tiobe.com/tiobe-index/"
          },
          {
            "text": "在线接口测试",
            "link": "https://www.fly63.com/php/http/"
          }
        ]
      },
      {
        "text": "TimeLine",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "关于",
        "icon": "reco-message",
        "items": [
          {
            "text": "GitHub",
            "link": "https://github.com/mlb123456",
            "icon": "reco-github"
          },
          {
            "text": "Gitee",
            "link": "https://gitee.com/mabobo123",
            "icon": "reco-mayun"
          }
        ]
      }
    ],
    "sidebar": {
      "/pages/VUE2.0/": [
        {
          "text": "Vue2.0",
          "title": "Vue2.0",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            "01_NPM包的安装与使用.md",
            "02_Vue核心概念.md",
            "03_常用指令使用.md",
            "04_事件修饰符、按键修饰符与系统修饰符.md",
            "05_计算属性与监听器、Vue实例的生命周期.md",
            "06_Vue实例常用的属性和方法.md",
            "07_自定义指令及过渡（动画）.md",
            "08_自定义过滤器及开发插件.md",
            "09_组件及组件之间的通信.md"
          ]
        }
      ]
    },
    "authorAvatar": "/assets/img/touxiang.png",
    "friendLink": [
      {
        "title": "vuepress-theme-reco",
        "desc": "A simple and beautiful vuepress Blog & Doc theme.",
        "logo": "/assets/img/niuyouguo.png",
        "link": "https://vuepress-theme-reco.recoluan.com"
      },
      {
        "title": "午后南杂",
        "logo": "/assets/img/niuyouguo.png",
        "desc": "Enjoy when you can, and endure when you must.",
        "email": "recoluan@qq.com",
        "link": "https://www.recoluan.com"
      }
    ],
    "valineConfig": {
      "appId": "39PXHFwCmvn8ItMgAgnemxNJ-gzGzoHsz",
      "appKey": "435FMrQ9VQY5rGV8KaE8mNIc",
      "placeholder": "填写邮箱地址可以及时收到回复噢...",
      "avatar": "wavatar",
      "visitor": true
    }
  }
}