/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-97ef0592",
        "v-9bf7d3aa",
        "v-da7c0ce4",
        "v-904c4292",
        "v-816bb714",
        "v-68d4cac8",
        "v-f44c8566",
        "v-05061389",
        "v-0cdd67c0"
      ]
    }
  },
  "categories": {
    "frontEnd": {
      "key": "frontEnd",
      "scope": "categories",
      "path": "/categories/frontEnd/",
      "pageKeys": [
        "v-97ef0592",
        "v-9bf7d3aa",
        "v-da7c0ce4",
        "v-904c4292",
        "v-816bb714",
        "v-68d4cac8",
        "v-f44c8566",
        "v-05061389",
        "v-0cdd67c0"
      ]
    }
  },
  "timeline": {}
}